//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace barberproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_items
    {
        public int id { get; set; }
        public int invoice_id { get; set; }
        public int item_id { get; set; }
    
        public virtual invoice invoice { get; set; }
        public virtual price_List price_List { get; set; }
    }
}
