//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace barberproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class permission
    {
        public int id { get; set; }
        public int worker_ID { get; set; }
        public Nullable<System.DateTime> date_permission { get; set; }
        public Nullable<int> persmission { get; set; }
    }
}
