//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace barberproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class workers_salary
    {
        public int id { get; set; }
        public int worker_id { get; set; }
        public System.TimeSpan in_time { get; set; }
        public Nullable<System.TimeSpan> out_time { get; set; }
        public Nullable<bool> Paid { get; set; }
        public Nullable<double> Bonus { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<double> deduction_out { get; set; }
        public Nullable<double> deduction_in { get; set; }
        public Nullable<int> working_minutes { get; set; }
        public Nullable<double> total_salary { get; set; }
        public Nullable<bool> permission__in { get; set; }
        public Nullable<bool> permission__out { get; set; }
        public Nullable<double> cal_min { get; set; }
    }
}
